// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBKW1ejt_Fj2xcCr_e9gcJ2gFVNnp3opaM',
//     appId: '1:944975109458:android:1b4dbd7f11800bf8702e8b',
//     messagingSenderId: '944975109458',
//     projectId: 'salestoolkitanalytics',
//     storageBucket: 'salestoolkitanalytics.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCKiODUegbZK0_CNluYUpNRJpoIeDoS-QI',
//     appId: '1:944975109458:ios:6fc007c9760ab52a702e8b',
//     messagingSenderId: '944975109458',
//     projectId: 'salestoolkitanalytics',
//     storageBucket: 'salestoolkitanalytics.appspot.com',
//     androidClientId: '944975109458-i53gqgptm595tjvnnurm6gf86r2n5cj6.apps.googleusercontent.com',
//     iosClientId: '944975109458-2vl6ro2dfom7splq0dg1jsbo4uugajru.apps.googleusercontent.com',
//     iosBundleId: 'com.creditdirect.salestoolkit',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCKiODUegbZK0_CNluYUpNRJpoIeDoS-QI',
//     appId: '1:944975109458:ios:5d51c1bd4a777f74702e8b',
//     messagingSenderId: '944975109458',
//     projectId: 'salestoolkitanalytics',
//     storageBucket: 'salestoolkitanalytics.appspot.com',
//     androidClientId: '944975109458-i53gqgptm595tjvnnurm6gf86r2n5cj6.apps.googleusercontent.com',
//     iosClientId: '944975109458-c3p4albgkhsuigd7hfogg7r38r35i60o.apps.googleusercontent.com',
//     iosBundleId: 'com.creditdirect.salesToolkit',
//   );
// }
